---
# Installs Docker Engine and compose plugin on Debian/Ubuntu

- name: Ensure apt transport packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture | default('amd64') }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install Docker Engine and compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Ensure docker service running
  service:
    name: docker
    state: started
    enabled: true
  when: ansible_os_family == 'Debian'

