version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rumah-integritas:local
    ports:
      - "80:80"
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Ensure DB connects to the compose service name below
      DB_CONNECTION: pgsql
      DB_HOST: pgsql
      DB_PORT: 5432
      # Safer defaults for containerized runtime
      SESSION_DRIVER: file
      CACHE_STORE: file
      # Auto run migrations + seed on startup
      AUTO_MIGRATE: "1"
      AUTO_SEED: "1"
      SEED_CLASS: Database\Seeders\AllInOneSeeder
    depends_on:
      - pgsql

  pgsql:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  pgdata:
